VALORES_CORRECTOS = {
    'BIEESTAR 50%': 'BIENESTAR 50%',
    'BIENENSTAR 50%': 'BIENESTAR 50%',
    'BIENESTAR 50 %': 'BIENESTAR 50%',
    'BIENESTAR 100 %': 'BIENESTAR 100%',
    'BIENESTAR 80$': 'BIENESTAR 80%',
    'BIENESTAR 80\'%': 'BIENESTAR 80%',
    'BIENESTAR 80&': 'BIENESTAR 80%',
    'BIENESTAR80%': 'BIENESTAR 80%',
    'BIENSTAR 80%': 'BIENESTAR 80%',
    'BINESTAR 80%': 'BIENESTAR 80%',
    'ESTUDIANTE BIENESTAR 80%': 'BIENESTAR 80%',
    'COLEGIO BARBARA MICARELLI': 'COLEGIO BARBARA MICARELLI PP',
    'COLEGIO PIONEROS PP': 'COLEGIO LOS PIONEROS PP',
    'COLEGIO LOS PIONEROS': 'COLEGIO LOS PIONEROS PP',
    'COMFEALCO CONTRALORIA': 'COMFENALCO CONTRALORIA',
    'COMFENALCO CONTROLORIA': 'COMFENALCO CONTRALORIA',
    'COMFENALCO BOTÓN DE PAGO': 'COMFENALCO BOTON DE PAGO',
    'CPMFENALCO BOTON DE PAGO': 'COMFENALCO BOTON DE PAGO',
    'COMFENALCO GESTIÓN HUMANA': 'COMFENALCO GESTION HUMANA',
    'COMGFNALCO GESTION HUMANA': 'COMFENALCO GESTION HUMANA',
    'COMFENALCO NAVITRASN': 'COMFENALCO NAVITRANS',
    'COMFENLACO NAVITRANS': 'COMFENALCO NAVITRANS',
    'COMFENALCO PAGA PACIENTE': 'COMFENALCO PP',
    'CONVENALCO PAGA PACIENTE': 'COMFENALCO PP',
    'COMFENLACO PP': 'COMFENALCO PP',
    'COMFENALCO SER FAMILIAS MAS': 'COMFENALCO SER FAMILIAS',
    'COMFENNALCO FISA': 'COMFENALCO FISA',
    'CONVENIO PAGA PACIENTE': 'CONVENIO PP',
    'EGRESADA': 'EGRESADO',
    'FAMILIAR EGRASADO': 'FAMILIAR EGRESADO',
    'ESTAUDIANTE': 'ESTUDIANTE',
    'ESTUDAINTE': 'ESTUDIANTE',
    'ESTUDIANTES': 'ESTUDIANTE',
    'FONDELCO (LOCERIA COLOMBIANA': 'FONDELCO',
    'FONDELCO (LOCERIA COLOMBIANA)': 'FONDELCO',
    'LICEO SALAZAR Y HERRERA PYP': 'LICEO SALAZAR Y HERRERA PP',
    'FUNDACION UDEA': 'FUNDACION U DE A',
    'LAM COSMETICOS': 'LAM COSMETICS',
    'GESTIÓN HUMANA': 'GESTION HUMANA',
    'PARICULAR': 'PARTICULAR',
    'NW STETIC S.A': 'NEW STETIC S.A',
    '143': 'Buenavista',
    '167': 'Cajibío',
    '43': 'Almeida'
}


#Columnas RIPS
TIPO_IDENTIFICACION = "tipo de identificacion"
FECHA_CONSULTA = "fecha de consulta"
NRO_AUTORIZACION = "nro de autorizacion"
CODIGO_CONSULTA = "codigo de la consulta"
FINALIDAD_CONSULTA = "finalidad de la consulta"
CAUSA_EXTERNA = "causa externa"
COD_DX_PRINCIPAL = "cod dx principal"
COD_DX_REL_1 = "cod dx rel 1"
COD_DX_REL_2 = "cod dx rel 2"
COD_DX_REL_3 = "cod dx rel 3"
TIPO_DIAGNOSTICO = "tipo de diagnostico"
VALOR_CONSULTA = "valor de la consulta"
VALOR_CUOTA_MODERADORA = "valor cuota moderadora"
VALOR_NETO_PAGAR = "valor neto a pagar"
IDENTIFICACION_ENCRIPTADA = "identificacion encriptada"

#Columnas Mensual
TIPO_IDENTIFICACION_PACIENTE = "Tipo de Identificación del Paciente"
CIUDAD = "Ciudad"
DIRECCION = "Dirección"
BARRIO = "Barrio"
CORREO_ELECTRONICO = "Correo Electrónico"
GENERO = "Género"
FECHA_NACIMIENTO = "Fecha Nacimiento"
EDAD = "Edad"
CONSECUTIVO = "Consecutivo"
ASUNTO = "Asunto"
TIPO_COMPROMISO = "Tipo de Compromiso"
FECHA_CITA = "Fecha de la Cita"
ESTADO_CITA = "Estado de la Cita"
TIPO_PROCEDIMIENTO = "Tipo de Procedimiento"
TIPO_USUARIO = "Tipo de Usuario"